name: Hello World
on: [push]
jobs:
  output_hello_world:
    name: Output Hello World
    steps:
    runs_on: Ubuntu-latest
    - uses: actions/checkout@v4
    - name: Run a script
    run: echo "Hello World!"
